dataset: ogbn-products
# model
hidden_size: 64
layer_num: 2
activation: relu
dropout: 0.5
model: GNN
encoder: GAT_Encoder
# training
lr: 0.001
weight_decay: 0.0005
epochs: 200
earlystop: False
patience: 20
